"""empty message

Revision ID: 50086b6ff000
Revises: 68b3176e7ad9
Create Date: 2021-06-13 03:42:01.026504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50086b6ff000'
down_revision = '68b3176e7ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Artist_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Venue_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Start_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Artist_ID'], ['Artist.id'], name='Show_Artist_ID_fkey'),
    sa.ForeignKeyConstraint(['Venue_ID'], ['Venue.id'], name='Show_Venue_ID_fkey'),
    sa.PrimaryKeyConstraint('id', 'Artist_ID', 'Venue_ID', name='Show_pkey')
    )
    # ### end Alembic commands ###
