"""empty message

Revision ID: 68b3176e7ad9
Revises: 746811bec4ff
Create Date: 2021-06-13 03:24:02.969540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b3176e7ad9'
down_revision = '746811bec4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'Artist_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Show', 'Venue_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'Venue_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'Artist_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
