"""empty message

Revision ID: 7df686473356
Revises: cc6d7a7c09d9
Create Date: 2021-06-11 15:32:27.791504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df686473356'
down_revision = 'cc6d7a7c09d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Artist_ID', sa.Integer(), nullable=False),
    sa.Column('Venue_ID', sa.Integer(), nullable=False),
    sa.Column('Start_Time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_ID'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_ID'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id', 'Artist_ID', 'Venue_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
