"""empty message

Revision ID: 89188a23d7a3
Revises: 7c897a849c01
Create Date: 2021-06-16 22:30:38.140026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89188a23d7a3'
down_revision = '7c897a849c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Artist_ID', sa.Integer(), nullable=False),
    sa.Column('Venue_ID', sa.Integer(), nullable=False),
    sa.Column('Start_Time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_ID'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_ID'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
