"""empty message

Revision ID: 8c4344629869
Revises: 50086b6ff000
Create Date: 2021-06-13 03:48:48.898696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4344629869'
down_revision = '50086b6ff000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Artist_ID', sa.Integer(), nullable=False),
    sa.Column('Venue_ID', sa.Integer(), nullable=False),
    sa.Column('Start_Time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_ID'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_ID'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id', 'Artist_ID', 'Venue_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
