"""empty message

Revision ID: b6a99a8354fe
Revises: 8c4344629869
Create Date: 2021-06-13 04:31:43.409490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a99a8354fe'
down_revision = '8c4344629869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'Artist_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Show', 'Venue_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'Venue_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'Artist_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
