"""empty message

Revision ID: e63299fff250
Revises: ab443afe9849
Create Date: 2021-06-14 23:57:55.123194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63299fff250'
down_revision = 'ab443afe9849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Genre_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Venue_Genre')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_table('Venue_Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Venue_Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Venue_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Venue_Genre_pkey')
    )
    op.drop_table('Genre')
    # ### end Alembic commands ###
