"""empty message

Revision ID: e67d0a036a78
Revises: ce86e5cabbc9
Create Date: 2021-06-12 18:26:03.587381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67d0a036a78'
down_revision = 'ce86e5cabbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Venue_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venue_Genre')
    # ### end Alembic commands ###
